<template>
  <v-textarea
      v-model="message"
      :label="$t('writeAMessage')"
      :placeholder="hint"
      rows="1"
      :auto-grow="autoGrow"
      :disabled="disabled"
      :loading="loading"
      :hide-details="true"
      append-inner-icon="send"
      @keyup.enter.exact="enterOnly"
      @click:appendInner="clickSe