<template>
  <v-dialog
      v-model="dialog"
      fullscreen
      :scrim="false"
      transition="dialog-bottom-transition"
  >
    <template v-slot:activator="{ props }">
      <v-list-item
          v-bind="props"
          rounded="xl"
          prepend-icon="language"
          :title="$t('language')"
      ></v-list-item>
    </template>
    <v-card>
      <v-toolbar
          dark
          color="primary"
      >
        <v-